package pe.edu.unmsm.veterinaria.clinica.entities;
// Generated 17/11/2015 10:49:36 PM by Hibernate Tools 4.0.0

/**
 * Analisismedico generated by hbm2java
 */
public class Analisismedico implements java.io.Serializable {

	private Integer idAnalisisMedico;
	private Atencionmedica atencionmedica;
	private Tipoanalisis tipoanalisis;
	private Clinicoveterinario clinicoveterinario;
	private String estadoAnalisisMedico;
	private String ucolor;
	private String uaspecto;
	private String udensidad;
	private String upH;
	private String uproteinas;
	private String uglucosa;
	private String uhemoglobina;
	private String unitritos;
	private String uleucocitos;
	private String ueritrocitos;
	private String ubacterias;
	private String uobservaciones;
	private String shematocrito;
	private String shemoglobina;
	private String sleucocitos;
	private String sneutrofilos;
	private String slinfocitos;
	private String splaquetas;
	private String sobservaciones;

	public Analisismedico() {
	}

	public Analisismedico(Atencionmedica atencionmedica, Tipoanalisis tipoanalisis) {
		this.atencionmedica = atencionmedica;
		this.tipoanalisis = tipoanalisis;
	}

	public Analisismedico(Atencionmedica atencionmedica, Tipoanalisis tipoanalisis,
			Clinicoveterinario clinicoveterinario, String estadoAnalisisMedico, String ucolor, String uaspecto,
			String udensidad, String upH, String uproteinas, String uglucosa, String uhemoglobina, String unitritos,
			String uleucocitos, String ueritrocitos, String ubacterias, String uobservaciones, String shematocrito,
			String shemoglobina, String sleucocitos, String sneutrofilos, String slinfocitos, String splaquetas,
			String sobservaciones) {
		this.atencionmedica = atencionmedica;
		this.tipoanalisis = tipoanalisis;
		this.clinicoveterinario = clinicoveterinario;
		this.estadoAnalisisMedico = estadoAnalisisMedico;
		this.ucolor = ucolor;
		this.uaspecto = uaspecto;
		this.udensidad = udensidad;
		this.upH = upH;
		this.uproteinas = uproteinas;
		this.uglucosa = uglucosa;
		this.uhemoglobina = uhemoglobina;
		this.unitritos = unitritos;
		this.uleucocitos = uleucocitos;
		this.ueritrocitos = ueritrocitos;
		this.ubacterias = ubacterias;
		this.uobservaciones = uobservaciones;
		this.shematocrito = shematocrito;
		this.shemoglobina = shemoglobina;
		this.sleucocitos = sleucocitos;
		this.sneutrofilos = sneutrofilos;
		this.slinfocitos = slinfocitos;
		this.splaquetas = splaquetas;
		this.sobservaciones = sobservaciones;
	}

	public Integer getIdAnalisisMedico() {
		return this.idAnalisisMedico;
	}

	public void setIdAnalisisMedico(Integer idAnalisisMedico) {
		this.idAnalisisMedico = idAnalisisMedico;
	}

	public Atencionmedica getAtencionmedica() {
		return this.atencionmedica;
	}

	public void setAtencionmedica(Atencionmedica atencionmedica) {
		this.atencionmedica = atencionmedica;
	}

	public Tipoanalisis getTipoanalisis() {
		return this.tipoanalisis;
	}

	public void setTipoanalisis(Tipoanalisis tipoanalisis) {
		this.tipoanalisis = tipoanalisis;
	}

	public Clinicoveterinario getClinicoveterinario() {
		return this.clinicoveterinario;
	}

	public void setClinicoveterinario(Clinicoveterinario clinicoveterinario) {
		this.clinicoveterinario = clinicoveterinario;
	}

	public String getEstadoAnalisisMedico() {
		return this.estadoAnalisisMedico;
	}

	public void setEstadoAnalisisMedico(String estadoAnalisisMedico) {
		this.estadoAnalisisMedico = estadoAnalisisMedico;
	}

	public String getUcolor() {
		return this.ucolor;
	}

	public void setUcolor(String ucolor) {
		this.ucolor = ucolor;
	}

	public String getUaspecto() {
		return this.uaspecto;
	}

	public void setUaspecto(String uaspecto) {
		this.uaspecto = uaspecto;
	}

	public String getUdensidad() {
		return this.udensidad;
	}

	public void setUdensidad(String udensidad) {
		this.udensidad = udensidad;
	}

	public String getUpH() {
		return this.upH;
	}

	public void setUpH(String upH) {
		this.upH = upH;
	}

	public String getUproteinas() {
		return this.uproteinas;
	}

	public void setUproteinas(String uproteinas) {
		this.uproteinas = uproteinas;
	}

	public String getUglucosa() {
		return this.uglucosa;
	}

	public void setUglucosa(String uglucosa) {
		this.uglucosa = uglucosa;
	}

	public String getUhemoglobina() {
		return this.uhemoglobina;
	}

	public void setUhemoglobina(String uhemoglobina) {
		this.uhemoglobina = uhemoglobina;
	}

	public String getUnitritos() {
		return this.unitritos;
	}

	public void setUnitritos(String unitritos) {
		this.unitritos = unitritos;
	}

	public String getUleucocitos() {
		return this.uleucocitos;
	}

	public void setUleucocitos(String uleucocitos) {
		this.uleucocitos = uleucocitos;
	}

	public String getUeritrocitos() {
		return this.ueritrocitos;
	}

	public void setUeritrocitos(String ueritrocitos) {
		this.ueritrocitos = ueritrocitos;
	}

	public String getUbacterias() {
		return this.ubacterias;
	}

	public void setUbacterias(String ubacterias) {
		this.ubacterias = ubacterias;
	}

	public String getUobservaciones() {
		return this.uobservaciones;
	}

	public void setUobservaciones(String uobservaciones) {
		this.uobservaciones = uobservaciones;
	}

	public String getShematocrito() {
		return this.shematocrito;
	}

	public void setShematocrito(String shematocrito) {
		this.shematocrito = shematocrito;
	}

	public String getShemoglobina() {
		return this.shemoglobina;
	}

	public void setShemoglobina(String shemoglobina) {
		this.shemoglobina = shemoglobina;
	}

	public String getSleucocitos() {
		return this.sleucocitos;
	}

	public void setSleucocitos(String sleucocitos) {
		this.sleucocitos = sleucocitos;
	}

	public String getSneutrofilos() {
		return this.sneutrofilos;
	}

	public void setSneutrofilos(String sneutrofilos) {
		this.sneutrofilos = sneutrofilos;
	}

	public String getSlinfocitos() {
		return this.slinfocitos;
	}

	public void setSlinfocitos(String slinfocitos) {
		this.slinfocitos = slinfocitos;
	}

	public String getSplaquetas() {
		return this.splaquetas;
	}

	public void setSplaquetas(String splaquetas) {
		this.splaquetas = splaquetas;
	}

	public String getSobservaciones() {
		return this.sobservaciones;
	}

	public void setSobservaciones(String sobservaciones) {
		this.sobservaciones = sobservaciones;
	}

}
