package pe.edu.unmsm.veterinaria.clinica.entities;
// Generated 17/11/2015 10:49:36 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Tipoanalisis generated by hbm2java
 */
public class Tipoanalisis implements java.io.Serializable {

	private Integer idTipoAnalisis;
	private String nombre;
	private Set analisismedicos = new HashSet(0);

	public Tipoanalisis() {
	}

	public Tipoanalisis(String nombre, Set analisismedicos) {
		this.nombre = nombre;
		this.analisismedicos = analisismedicos;
	}

	public Integer getIdTipoAnalisis() {
		return this.idTipoAnalisis;
	}

	public void setIdTipoAnalisis(Integer idTipoAnalisis) {
		this.idTipoAnalisis = idTipoAnalisis;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getAnalisismedicos() {
		return this.analisismedicos;
	}

	public void setAnalisismedicos(Set analisismedicos) {
		this.analisismedicos = analisismedicos;
	}

}
