package cfg.hibernate;

// Generated 2015-6-16 1:29:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Beanreader generated by hbm2java
 */
public class Beanreader implements java.io.Serializable {

	private String readerid;
	private Beansystemuser beansystemuserByCreatorUserId;
	private Beansystemuser beansystemuserByRemoverUserId;
	private Beansystemuser beansystemuserByStopUserId;
	private String readerName;
	private int readerTypeId;
	private int lendBookLimitted;
	private Date createDate;
	private Date removeDate;
	private Date stopDate;
	private Set beanreserves = new HashSet(0);
	private Set beanbooklendrecords = new HashSet(0);
	private String state;
	private String readerType;
	private Long count;
	private Double penalSum;


	public Beanreader() {
	}

	public Beanreader(String readerid,
			Beansystemuser beansystemuserByCreatorUserId, String readerName,
			int readerTypeId, int lendBookLimitted, Date createDate) {
		this.readerid = readerid;
		this.beansystemuserByCreatorUserId = beansystemuserByCreatorUserId;
		this.readerName = readerName;
		this.readerTypeId = readerTypeId;
		this.lendBookLimitted = lendBookLimitted;
		this.createDate = createDate;
	}

	public Beanreader(String readerid,
			Beansystemuser beansystemuserByCreatorUserId,
			Beansystemuser beansystemuserByRemoverUserId,
			Beansystemuser beansystemuserByStopUserId, String readerName,
			int readerTypeId, int lendBookLimitted, Date createDate,
			Date removeDate, Date stopDate, Set beanreserves,
			Set beanbooklendrecords) {
		this.readerid = readerid;
		this.beansystemuserByCreatorUserId = beansystemuserByCreatorUserId;
		this.beansystemuserByRemoverUserId = beansystemuserByRemoverUserId;
		this.beansystemuserByStopUserId = beansystemuserByStopUserId;
		this.readerName = readerName;
		this.readerTypeId = readerTypeId;
		this.lendBookLimitted = lendBookLimitted;
		this.createDate = createDate;
		this.removeDate = removeDate;
		this.stopDate = stopDate;
		this.beanreserves = beanreserves;
		this.beanbooklendrecords = beanbooklendrecords;
	}

	public String getReaderid() {
		return this.readerid;
	}

	public void setReaderid(String readerid) {
		this.readerid = readerid;
	}

	public Beansystemuser getBeansystemuserByCreatorUserId() {
		return this.beansystemuserByCreatorUserId;
	}

	public void setBeansystemuserByCreatorUserId(
			Beansystemuser beansystemuserByCreatorUserId) {
		this.beansystemuserByCreatorUserId = beansystemuserByCreatorUserId;
	}

	public Beansystemuser getBeansystemuserByRemoverUserId() {
		return this.beansystemuserByRemoverUserId;
	}

	public void setBeansystemuserByRemoverUserId(
			Beansystemuser beansystemuserByRemoverUserId) {
		this.beansystemuserByRemoverUserId = beansystemuserByRemoverUserId;
	}

	public Beansystemuser getBeansystemuserByStopUserId() {
		return this.beansystemuserByStopUserId;
	}

	public void setBeansystemuserByStopUserId(
			Beansystemuser beansystemuserByStopUserId) {
		this.beansystemuserByStopUserId = beansystemuserByStopUserId;
	}

	public String getReaderName() {
		return this.readerName;
	}

	public void setReaderName(String readerName) {
		this.readerName = readerName;
	}

	public int getReaderTypeId() {
		return this.readerTypeId;
	}

	public void setReaderTypeId(int readerTypeId) {
		this.readerTypeId = readerTypeId;
	}

	public int getLendBookLimitted() {
		return this.lendBookLimitted;
	}

	public void setLendBookLimitted(int lendBookLimitted) {
		this.lendBookLimitted = lendBookLimitted;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getRemoveDate() {
		return this.removeDate;
	}

	public void setRemoveDate(Date removeDate) {
		this.removeDate = removeDate;
	}

	public Date getStopDate() {
		return this.stopDate;
	}

	public void setStopDate(Date stopDate) {
		this.stopDate = stopDate;
	}

	public Set getBeanreserves() {
		return this.beanreserves;
	}

	public void setBeanreserves(Set beanreserves) {
		this.beanreserves = beanreserves;
	}

	public Set getBeanbooklendrecords() {
		return this.beanbooklendrecords;
	}

	public void setBeanbooklendrecords(Set beanbooklendrecords) {
		this.beanbooklendrecords = beanbooklendrecords;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getReaderType() {
		return readerType;
	}

	public void setReaderType(String readerType) {
		this.readerType = readerType;
	}

	public Long getCount() {
		return count;
	}

	public void setCount(Long count) {
		this.count = count;
	}
	
	public Double getPenalSum() {
		return penalSum;
	}

	public void setPenalSum(Double penalSum) {
		this.penalSum = penalSum;
	}
}
