package cfg.hibernate;

// Generated 2015-6-16 1:29:29 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Beanbook generated by hbm2java
 */
public class Beanbook implements java.io.Serializable {

	private String barcode;
	private Beanpublisher beanpublisher;
	private String bookname;
	private double price;
	private String state;
	private Set beanbooklendrecords = new HashSet(0);
	private Set beanreserves = new HashSet(0);
	private String publisher;
	private Long count;

	public Beanbook() {
	}

	public Beanbook(String barcode, String bookname, double price, String state) {
		this.barcode = barcode;
		this.bookname = bookname;
		this.price = price;
		this.state = state;
	}

	public Beanbook(String barcode, Beanpublisher beanpublisher,
			String bookname, double price, String state,
			Set beanbooklendrecords, Set beanreserves) {
		this.barcode = barcode;
		this.beanpublisher = beanpublisher;
		this.bookname = bookname;
		this.price = price;
		this.state = state;
		this.beanbooklendrecords = beanbooklendrecords;
		this.beanreserves = beanreserves;
	}

	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	public Beanpublisher getBeanpublisher() {
		return this.beanpublisher;
	}

	public void setBeanpublisher(Beanpublisher beanpublisher) {
		this.beanpublisher = beanpublisher;
	}

	public String getBookname() {
		return this.bookname;
	}

	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Set getBeanbooklendrecords() {
		return this.beanbooklendrecords;
	}

	public void setBeanbooklendrecords(Set beanbooklendrecords) {
		this.beanbooklendrecords = beanbooklendrecords;
	}

	public Set getBeanreserves() {
		return this.beanreserves;
	}

	public void setBeanreserves(Set beanreserves) {
		this.beanreserves = beanreserves;
	}

	public String getPublisher() {
		return publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Long getCount() {
		return count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

}
