package cfg.hibernate;

// Generated 2015-6-16 1:29:29 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Beanpublisher generated by hbm2java
 */
public class Beanpublisher implements java.io.Serializable {

	private String pubid;
	private String publisherName;
	private String address;
	private Set beanbooks = new HashSet(0);

	public Beanpublisher() {
	}

	public Beanpublisher(String pubid, String publisherName) {
		this.pubid = pubid;
		this.publisherName = publisherName;
	}

	public Beanpublisher(String pubid, String publisherName, String address,
			Set beanbooks) {
		this.pubid = pubid;
		this.publisherName = publisherName;
		this.address = address;
		this.beanbooks = beanbooks;
	}

	public String getPubid() {
		return this.pubid;
	}

	public void setPubid(String pubid) {
		this.pubid = pubid;
	}

	public String getPublisherName() {
		return this.publisherName;
	}

	public void setPublisherName(String publisherName) {
		this.publisherName = publisherName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set getBeanbooks() {
		return this.beanbooks;
	}

	public void setBeanbooks(Set beanbooks) {
		this.beanbooks = beanbooks;
	}

}
