package cfg.hibernate;

// Generated 2015-6-16 1:29:29 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Beanreserve generated by hbm2java
 */
public class Beanreserve implements java.io.Serializable {

	private Integer reserveid;
	private Beanreader beanreader;
	private Beanbook beanbook;
	private Date reserveDate;
	private Date cancelDate;

	public Beanreserve() {
	}

	public Beanreserve(Beanreader beanreader, Beanbook beanbook,
			Date reserveDate) {
		this.beanreader = beanreader;
		this.beanbook = beanbook;
		this.reserveDate = reserveDate;
	}

	public Beanreserve(Beanreader beanreader, Beanbook beanbook,
			Date reserveDate, Date cancelDate) {
		this.beanreader = beanreader;
		this.beanbook = beanbook;
		this.reserveDate = reserveDate;
		this.cancelDate = cancelDate;
	}

	public Integer getReserveid() {
		return this.reserveid;
	}

	public void setReserveid(Integer reserveid) {
		this.reserveid = reserveid;
	}

	public Beanreader getBeanreader() {
		return this.beanreader;
	}

	public void setBeanreader(Beanreader beanreader) {
		this.beanreader = beanreader;
	}

	public Beanbook getBeanbook() {
		return this.beanbook;
	}

	public void setBeanbook(Beanbook beanbook) {
		this.beanbook = beanbook;
	}

	public Date getReserveDate() {
		return this.reserveDate;
	}

	public void setReserveDate(Date reserveDate) {
		this.reserveDate = reserveDate;
	}

	public Date getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(Date cancelDate) {
		this.cancelDate = cancelDate;
	}

}
