package cfg.hibernate;

// Generated 2015-6-16 1:29:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Beansystemuser generated by hbm2java
 */
public class Beansystemuser implements java.io.Serializable {

	private String userid;
	private String username;
	private String pwd;
	private String usertype;
	private Date createDate;
	private Date removeDate;
	private Set beanbooklendrecordsForLendOperUserid = new HashSet(0);
	private Set beanreadersForRemoverUserId = new HashSet(0);
	private Set beanreadersForCreatorUserId = new HashSet(0);
	private Set beanbooklendrecordsForReturnOperUserid = new HashSet(0);
	private Set beanreadersForStopUserId = new HashSet(0);

	public Beansystemuser() {
	}

	public Beansystemuser(String userid, String username, String pwd,
			String usertype, Date createDate) {
		this.userid = userid;
		this.username = username;
		this.pwd = pwd;
		this.usertype = usertype;
		this.createDate = createDate;
	}

	public Beansystemuser(String userid, String username, String pwd,
			String usertype, Date createDate, Date removeDate,
			Set beanbooklendrecordsForLendOperUserid,
			Set beanreadersForRemoverUserId, Set beanreadersForCreatorUserId,
			Set beanbooklendrecordsForReturnOperUserid,
			Set beanreadersForStopUserId) {
		this.userid = userid;
		this.username = username;
		this.pwd = pwd;
		this.usertype = usertype;
		this.createDate = createDate;
		this.removeDate = removeDate;
		this.beanbooklendrecordsForLendOperUserid = beanbooklendrecordsForLendOperUserid;
		this.beanreadersForRemoverUserId = beanreadersForRemoverUserId;
		this.beanreadersForCreatorUserId = beanreadersForCreatorUserId;
		this.beanbooklendrecordsForReturnOperUserid = beanbooklendrecordsForReturnOperUserid;
		this.beanreadersForStopUserId = beanreadersForStopUserId;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getRemoveDate() {
		return this.removeDate;
	}

	public void setRemoveDate(Date removeDate) {
		this.removeDate = removeDate;
	}

	public Set getBeanbooklendrecordsForLendOperUserid() {
		return this.beanbooklendrecordsForLendOperUserid;
	}

	public void setBeanbooklendrecordsForLendOperUserid(
			Set beanbooklendrecordsForLendOperUserid) {
		this.beanbooklendrecordsForLendOperUserid = beanbooklendrecordsForLendOperUserid;
	}

	public Set getBeanreadersForRemoverUserId() {
		return this.beanreadersForRemoverUserId;
	}

	public void setBeanreadersForRemoverUserId(Set beanreadersForRemoverUserId) {
		this.beanreadersForRemoverUserId = beanreadersForRemoverUserId;
	}

	public Set getBeanreadersForCreatorUserId() {
		return this.beanreadersForCreatorUserId;
	}

	public void setBeanreadersForCreatorUserId(Set beanreadersForCreatorUserId) {
		this.beanreadersForCreatorUserId = beanreadersForCreatorUserId;
	}

	public Set getBeanbooklendrecordsForReturnOperUserid() {
		return this.beanbooklendrecordsForReturnOperUserid;
	}

	public void setBeanbooklendrecordsForReturnOperUserid(
			Set beanbooklendrecordsForReturnOperUserid) {
		this.beanbooklendrecordsForReturnOperUserid = beanbooklendrecordsForReturnOperUserid;
	}

	public Set getBeanreadersForStopUserId() {
		return this.beanreadersForStopUserId;
	}

	public void setBeanreadersForStopUserId(Set beanreadersForStopUserId) {
		this.beanreadersForStopUserId = beanreadersForStopUserId;
	}

}
